rabbitmq:
  host: "localhost"
  port: 5552
  user: "guest"
  password: "guest"
input_stream:
  #name: "symbol_input_streams"
  name: "symbol_input_streams"
output_stream:
  name: "symbol_output_streams"